import {ClerkProvider, Show, SignInButton, SignUpButton, UserButton} from "@clerk/nextjs";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`dark ${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <ClerkProvider
          appearance={{
            variables: {
              colorBackground: "oklch(0.145 0 0)",
              colorInputBackground: "oklch(0.205 0 0)",
              colorInputText: "oklch(0.985 0 0)",
              colorText: "oklch(0.985 0 0)",
              colorTextSecondary: "oklch(0.708 0 0)",
              colorPrimary: "oklch(0.922 0 0)",
              colorNeutral: "oklch(0.985 0 0)",
              colorDanger: "oklch(0.704 0.191 22.216)",
              colorBorder: "oklch(1 0 0 / 10%)",
              borderRadius: "0.625rem",
            },
          }}
        >
          <header className="flex h-16 items-center justify-end gap-4 border-b px-4">
            <Show when="signed-out">
              <SignInButton mode="modal" />
              <SignUpButton mode="modal" />
            </Show>
            <Show when="signed-in">
              <UserButton />
            </Show>
          </header>
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}